/**:
  ros__parameters:
    update_rate: 10.0
    accel_ratio: 1.0
    brake_ratio: 1.0
    steer_ratio: 0.26
    steering_angle_velocity: 0.01
    accel_sensitivity: 1.0
    brake_sensitivity: 1.0
    control_command:
      velocity_gain: 0.0
      max_forward_velocity: 22.0
      max_backward_velocity: 8.0
      backward_accel_ratio: 1.0
